### ISSUE TITLE
How to link with OpenMP?

### ISSUE THREAD

**Issue by pornel** [alexcrichton/cc-rs#266]
OpenMP is special in that it requires `-fopenmp` to be passed to the linker (`-lopenmp` won't work).

`cc.flag('-fopenmp')` is passed only to the compiler, but not the linker. AFAIK cargo doesn't allow arbitrary linker flags.

Is is possible to use OpenMP with build scripts/cargo?

**Comment by pornel** [comment]
OK, got it:

```rust
            println!("cargo:rustc-link-lib=gomp");
```

~/.cargo/config

```toml
[target.x86_64-apple-darwin]
linker = "gcc-7"
```
