### ISSUE TITLE
Support integration with vcpkg (the crate) for dependency resolution

### ISSUE THREAD

**Issue by cdecompilador** [alexcrichton/cc-rs#630]
With this having c/c++ sources that requires some specific dependency would be just:
Example of what it should look like (it doesn't need to be windows the target os but makes code simpler):

**Cargo.toml**
```toml
[build-depenencies]
cc = "*"
vcpkg = "*"

[package.metadata.vcpkg]
install = ["sdl2:x64-windows-static"]
git = "..."
rev = "..."
```

**build.rs**
```rust
fn main() {
    let sdl_lib = vcpkg::Config::new()
        .target_triplet("x64-windows-static")
        .find_package("sdl2").unwrap();
    
    cc::Build::new()
        .target("x86_64-pc-windows-msvc")
        .integrate(sdl_lib) // Here comes the magic to implement
        .file("main.c")
        .compile("foo");
}
```

Then just running this commands should generate a `foo.exe` than opens an sdl window (than can be used from the rust project itself):
```shell
cargo vcpkg build
```

```shell
cargo b
```
